M48
; DRILL file {KiCad 8.0.3} date 2024-09-21T22:38:26+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-21T22:38:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0460
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1181
%
G90
G05
T1
X6.6043Y-4.5476
X6.6043Y-4.8232
T2
X6.533Y-4.1311
X6.533Y-4.2311
T3
X4.778Y-3.9205
X5.1993Y-3.9205
M30
